Add a really smooth and cool transition
VictorWinberg/qr-hunt pull request #54
Opened 2021-02-07 20:39 UTC by AnnieLeonia

2021-02-07 21:12 UTC, VictorWinberg requested changes

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +        <div class="qrspot--info--raiting">
```suggestion
      <div class="qrspot-title">{{ currentSpot.title }}</div>
      <div class="qrspot-info">
        <div class="qrspot-info__distance">
          <img alt="My Location" class="distance-icon" :src="distanceIcon" />
          <span>{{ distanceToMarker() }}</span>
        </div>
        <div class="qrspot-info__rating">
```

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +
Un-nest classes (except `.distance-icon` and `.star-icon`)

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +    .qrspot--title {
```suggestion
    .qrspot-title {
```

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +    .qrspot--info {
```suggestion
    .qrspot-info {
```

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +      .qrspot--info--distance {
```suggestion
      .qrspot-info__distance {
```

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +      .qrspot--info--raiting {
```suggestion
      .qrspot-info__rating {
```

2021-02-07 21:12 UTC, VictorWinberg commented on client/src/components/GoogleMaps.vue
> +      // this.map.controls[BOTTOM].push(informationBoxDiv);
Anything to save?

2021-02-08 07:50 UTC, AnnieLeonia commented on client/src/components/GoogleMaps.vue
> +      // this.map.controls[BOTTOM].push(informationBoxDiv);
Not really, I have removed it!

2021-02-08 07:55 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +        <div class="qrspot-info__raiting">
```suggestion
        <div class="qrspot-info__rating">
```

2021-02-08 07:55 UTC, VictorWinberg commented on client/src/components/CurrentSpot.vue
> +.qrspot-info__raiting {
```suggestion
.qrspot-info__rating {
```

2021-02-08 07:56 UTC, VictorWinberg approved these changes
LGTM 😎

2021-02-08 07:59 UTC, merged